services:
  redis:
    image: redis:latest
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
    ports:
      - "4000:4000"
      - "3000:3000"
    depends_on:
      - redis
    entrypoint: ["bun", "run", "src/index.ts"]
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/trpc"]
      interval: 30s
      retries: 3
      start_period: 30s
      timeout: 10s

volumes:
  redis-data:
